// ARCHIVO TEMPORAL — sólo para el torneo de diseño de PriorizacionScouting.
// NO se importa desde ningún componente de producción. Se elimina junto con
// el resto de src/components/monitoreo/tournament/ al cerrar el torneo.
//
// Fixture realista y determinístico (sin fechas relativas a "hoy") para que
// las 4 propuestas de diseño se comparen con exactamente los mismos datos.

import type { PriorizacionEntry } from '../../../utils/priorizacionMonitoreo';

export const FIXTURE_ENTRIES: PriorizacionEntry[] = [
  // --- Bracket 0: Tier A 'over' — máxima urgencia ---
  {
    sublote_id: 's-lavega-3', sublote_nombre: 'Sublote 3', lote_id: 'l-lavega', lote_nombre: '4. La Vega',
    pest_id: 'p-acaro', pest_nombre: 'Complejo de ácaros', grupo_key: 'acaro_complex',
    tier: 'A', estadoUmbral: 'over', umbralPct: 33, umbralSourceLabel: 'Cartama',
    incidenciaActual: 65.7, incidenciaAnterior: 52.1, cambio: 26.1, cambioFormateado: '(+26.1%)',
    tendencia: 'subiendo', temporadaAlta: true, historicalTier: 'High', weekOfYear: 14,
    diasDesdeUltimaFumigacion: 21, numRondas: 5,
    why: '66% ≥ umbral económico Cartama de Complejo de ácaros (33%), subiendo, en temporada alta histórica',
    bracket: 0,
  },
  {
    sublote_id: 's-australia-1', sublote_nombre: 'Sublote 1', lote_id: 'l-australia', lote_nombre: '3. Australia',
    pest_id: 'p-acaro', pest_nombre: 'Complejo de ácaros', grupo_key: 'acaro_complex',
    tier: 'A', estadoUmbral: 'over', umbralPct: 33, umbralSourceLabel: 'Cartama',
    incidenciaActual: 62.9, incidenciaAnterior: 49.0, cambio: 28.4, cambioFormateado: '(+28.4%)',
    tendencia: 'subiendo', temporadaAlta: true, historicalTier: 'High', weekOfYear: 14,
    diasDesdeUltimaFumigacion: 26, numRondas: 4,
    why: '63% ≥ umbral económico Cartama de Complejo de ácaros (33%), subiendo, en temporada alta histórica',
    bracket: 0,
  },
  {
    sublote_id: 's-lavega-3-cm', sublote_nombre: 'Sublote 3', lote_id: 'l-lavega', lote_nombre: '4. La Vega',
    pest_id: 'p-marceno', pest_nombre: 'Cucarron marceño', grupo_key: null,
    tier: 'A', estadoUmbral: 'over', umbralPct: 36, umbralSourceLabel: 'Cartama',
    incidenciaActual: 42.9, incidenciaAnterior: 38.0, cambio: 12.9, cambioFormateado: '(+12.9%)',
    tendencia: 'subiendo', temporadaAlta: false, historicalTier: 'Med', weekOfYear: 14,
    diasDesdeUltimaFumigacion: 21, numRondas: 3,
    why: '43% ≥ umbral económico Cartama de Cucarron marceño (36%), subiendo',
    bracket: 0,
  },
  {
    sublote_id: 's-tequendama-2', sublote_nombre: 'Sublote 2', lote_id: 'l-tequendama', lote_nombre: '2. Salto de Tequendama',
    pest_id: 'p-monalonion', pest_nombre: 'Monalonion', grupo_key: null,
    tier: 'A', estadoUmbral: 'over', umbralPct: 26, umbralSourceLabel: 'Cartama',
    incidenciaActual: 34.3, incidenciaAnterior: 30.1, cambio: 14.0, cambioFormateado: '(+14.0%)',
    tendencia: 'subiendo', temporadaAlta: false, historicalTier: 'Med', weekOfYear: 14,
    diasDesdeUltimaFumigacion: 14, numRondas: 6,
    why: '34% ≥ umbral económico Cartama de Monalonion (26%), subiendo',
    bracket: 0,
  },
  // --- Bracket 1: Tier A 'approaching' ---
  {
    sublote_id: 's-acueducto-1', sublote_nombre: 'Sublote 1', lote_id: 'l-acueducto', lote_nombre: '1. Acueducto',
    pest_id: 'p-trips', pest_nombre: 'Trips', grupo_key: null,
    tier: 'A', estadoUmbral: 'approaching', umbralPct: 1, umbralSourceLabel: 'Cartama',
    incidenciaActual: 0.85, incidenciaAnterior: 0.6, cambio: 41.7, cambioFormateado: '(+41.7%)',
    tendencia: 'subiendo', temporadaAlta: false, historicalTier: 'Low', weekOfYear: 14,
    diasDesdeUltimaFumigacion: 9, numRondas: 4,
    why: '1% se acerca al umbral económico Cartama de Trips (1%), subiendo',
    bracket: 1,
  },
  {
    sublote_id: 's-lavega-2', sublote_nombre: 'Sublote 2', lote_id: 'l-lavega', lote_nombre: '4. La Vega',
    pest_id: 'p-phytophtora', pest_nombre: 'Phytophtora', grupo_key: null,
    tier: 'A', estadoUmbral: 'approaching', umbralPct: 10, umbralSourceLabel: 'Cartama',
    incidenciaActual: 8.6, incidenciaAnterior: 7.0, cambio: 22.9, cambioFormateado: '(+22.9%)',
    tendencia: 'subiendo', temporadaAlta: false, historicalTier: 'Med', weekOfYear: 14,
    diasDesdeUltimaFumigacion: 21, numRondas: 3,
    why: '9% se acerca al umbral económico Cartama de Phytophtora (10%), subiendo',
    bracket: 1,
  },
  // --- Bracket 2: Tier B 'Alta' (sin umbral validado) ---
  {
    sublote_id: 's-tequendama-1', sublote_nombre: 'Sublote 1', lote_id: 'l-tequendama', lote_nombre: '2. Salto de Tequendama',
    pest_id: 'p-mosca-ovario', pest_nombre: 'Mosca del ovario', grupo_key: null,
    tier: 'B', gravedad: { texto: 'Alta', numerica: 3 },
    incidenciaActual: 90.0, incidenciaAnterior: 78.0, cambio: 15.4, cambioFormateado: '(+15.4%)',
    tendencia: 'subiendo', temporadaAlta: false, historicalTier: 'Med', weekOfYear: 14,
    diasDesdeUltimaFumigacion: null, numRondas: 3,
    why: 'Gravedad Alta (90%) para Mosca del ovario, sin umbral económico validado, subiendo',
    bracket: 2,
  },
  {
    sublote_id: 's-australia-3', sublote_nombre: 'Sublote 3', lote_id: 'l-australia', lote_nombre: '3. Australia',
    pest_id: 'p-antracnosis-ramas', pest_nombre: 'Antracnosis ramas', grupo_key: null,
    tier: 'B', gravedad: { texto: 'Alta', numerica: 3 },
    incidenciaActual: 38.0, incidenciaAnterior: 35.0, cambio: 8.6, cambioFormateado: '(+8.6%)',
    tendencia: 'estable', temporadaAlta: false, historicalTier: 'Low', weekOfYear: 14,
    diasDesdeUltimaFumigacion: 26, numRondas: 2,
    why: 'Gravedad Alta (38%) para Antracnosis ramas, sin umbral económico validado, estable',
    bracket: 2,
  },
  // --- Bracket 3: Tier A 'under' ---
  {
    sublote_id: 's-acueducto-2', sublote_nombre: 'Sublote 2', lote_id: 'l-acueducto', lote_nombre: '1. Acueducto',
    pest_id: 'p-antracnosis-fruto', pest_nombre: 'Antracnosis fruto', grupo_key: null,
    tier: 'A', estadoUmbral: 'under', umbralPct: 10, umbralSourceLabel: 'Cartama',
    incidenciaActual: 3.1, incidenciaAnterior: 4.0, cambio: -22.5, cambioFormateado: '(-22.5%)',
    tendencia: 'bajando', temporadaAlta: false, historicalTier: 'Low', weekOfYear: 14,
    diasDesdeUltimaFumigacion: 9, numRondas: 4,
    why: '3% por debajo del umbral económico Cartama de Antracnosis fruto (10%), bajando',
    bracket: 3,
  },
  {
    sublote_id: 's-tequendama-2-tr', sublote_nombre: 'Sublote 2', lote_id: 'l-tequendama', lote_nombre: '2. Salto de Tequendama',
    pest_id: 'p-trips', pest_nombre: 'Trips', grupo_key: null,
    tier: 'A', estadoUmbral: 'under', umbralPct: 1, umbralSourceLabel: 'Cartama',
    incidenciaActual: 0.1, incidenciaAnterior: 0.2, cambio: -50.0, cambioFormateado: '(-50.0%)',
    tendencia: 'estable', temporadaAlta: false, historicalTier: 'Low', weekOfYear: 14,
    diasDesdeUltimaFumigacion: 14, numRondas: 5,
    why: '0% por debajo del umbral económico Cartama de Trips (1%), estable',
    bracket: 3,
  },
  // --- Bracket 4: Tier B 'Media' ---
  {
    sublote_id: 's-lavega-1', sublote_nombre: 'Sublote 1', lote_id: 'l-lavega', lote_nombre: '4. La Vega',
    pest_id: 'p-mosca-ovario-2', pest_nombre: 'Mosca del ovario', grupo_key: null,
    tier: 'B', gravedad: { texto: 'Media', numerica: 2 },
    incidenciaActual: 18.0, incidenciaAnterior: 20.0, cambio: -10.0, cambioFormateado: '(-10.0%)',
    tendencia: 'bajando', temporadaAlta: false, historicalTier: 'Med', weekOfYear: 14,
    diasDesdeUltimaFumigacion: 21, numRondas: 3,
    why: 'Gravedad Media (18%) para Mosca del ovario, sin umbral económico validado, bajando',
    bracket: 4,
  },
  {
    sublote_id: 's-acueducto-3', sublote_nombre: 'Sublote 3', lote_id: 'l-acueducto', lote_nombre: '1. Acueducto',
    pest_id: 'p-antracnosis-ramas-2', pest_nombre: 'Antracnosis ramas', grupo_key: null,
    tier: 'B', gravedad: { texto: 'Media', numerica: 2 },
    incidenciaActual: 15.5, incidenciaAnterior: 14.0, cambio: 10.7, cambioFormateado: '(+10.7%)',
    tendencia: 'estable', temporadaAlta: false, historicalTier: 'Low', weekOfYear: 14,
    diasDesdeUltimaFumigacion: 9, numRondas: 2,
    why: 'Gravedad Media (16%) para Antracnosis ramas, sin umbral económico validado, estable',
    bracket: 4,
  },
  // --- Bracket 5: Tier B 'Baja' — mayoría de combinaciones, bajo riesgo ---
  {
    sublote_id: 's-australia-2', sublote_nombre: 'Sublote 2', lote_id: 'l-australia', lote_nombre: '3. Australia',
    pest_id: 'p-monalonion-2', pest_nombre: 'Monalonion', grupo_key: null,
    tier: 'B', gravedad: { texto: 'Baja', numerica: 1 },
    incidenciaActual: 4.2, incidenciaAnterior: 5.0, cambio: -16.0, cambioFormateado: '(-16.0%)',
    tendencia: 'bajando', temporadaAlta: false, historicalTier: 'Low', weekOfYear: 14,
    diasDesdeUltimaFumigacion: 26, numRondas: 3,
    why: 'Gravedad Baja (4%) para Monalonion, sin umbral económico validado, bajando',
    bracket: 5,
  },
  {
    sublote_id: 's-tequendama-1-ph', sublote_nombre: 'Sublote 1', lote_id: 'l-tequendama', lote_nombre: '2. Salto de Tequendama',
    pest_id: 'p-phytophtora-2', pest_nombre: 'Phytophtora', grupo_key: null,
    tier: 'A', estadoUmbral: 'under', umbralPct: 10, umbralSourceLabel: 'Cartama',
    incidenciaActual: 1.2, incidenciaAnterior: 1.5, cambio: -20.0, cambioFormateado: '(-20.0%)',
    tendencia: 'estable', temporadaAlta: false, historicalTier: 'Low', weekOfYear: 14,
    diasDesdeUltimaFumigacion: 14, numRondas: 4,
    why: '1% por debajo del umbral económico Cartama de Phytophtora (10%), estable',
    bracket: 3,
  },
  {
    sublote_id: 's-lavega-1-cm', sublote_nombre: 'Sublote 1', lote_id: 'l-lavega', lote_nombre: '4. La Vega',
    pest_id: 'p-marceno-2', pest_nombre: 'Cucarron marceño', grupo_key: null,
    tier: 'A', estadoUmbral: 'under', umbralPct: 36, umbralSourceLabel: 'Cartama',
    incidenciaActual: 12.0, incidenciaAnterior: 15.0, cambio: -20.0, cambioFormateado: '(-20.0%)',
    tendencia: 'bajando', temporadaAlta: false, historicalTier: 'Low', weekOfYear: 14,
    diasDesdeUltimaFumigacion: 21, numRondas: 3,
    why: '12% por debajo del umbral económico Cartama de Cucarron marceño (36%), bajando',
    bracket: 3,
  },
  {
    sublote_id: 's-acueducto-1-ac', sublote_nombre: 'Sublote 1', lote_id: 'l-acueducto', lote_nombre: '1. Acueducto',
    pest_id: 'p-acaro-2', pest_nombre: 'Complejo de ácaros', grupo_key: 'acaro_complex',
    tier: 'A', estadoUmbral: 'under', umbralPct: 33, umbralSourceLabel: 'Cartama',
    incidenciaActual: 6.0, incidenciaAnterior: 7.5, cambio: -20.0, cambioFormateado: '(-20.0%)',
    tendencia: 'bajando', temporadaAlta: false, historicalTier: 'Low', weekOfYear: 14,
    diasDesdeUltimaFumigacion: 9, numRondas: 4,
    why: '6% por debajo del umbral económico Cartama de Complejo de ácaros (33%), bajando',
    bracket: 3,
  },
  {
    sublote_id: 's-australia-1-tr', sublote_nombre: 'Sublote 1', lote_id: 'l-australia', lote_nombre: '3. Australia',
    pest_id: 'p-trips-2', pest_nombre: 'Trips', grupo_key: null,
    tier: 'A', estadoUmbral: 'under', umbralPct: 1, umbralSourceLabel: 'Cartama',
    incidenciaActual: 0.3, incidenciaAnterior: 0.3, cambio: 0, cambioFormateado: '(+0.0%)',
    tendencia: 'estable', temporadaAlta: false, historicalTier: 'Low', weekOfYear: 14,
    diasDesdeUltimaFumigacion: 26, numRondas: 5,
    why: '0% por debajo del umbral económico Cartama de Trips (1%), estable',
    bracket: 3,
  },
  {
    sublote_id: 's-tequendama-2-mo', sublote_nombre: 'Sublote 2', lote_id: 'l-tequendama', lote_nombre: '2. Salto de Tequendama',
    pest_id: 'p-mosca-ovario-3', pest_nombre: 'Mosca del ovario', grupo_key: null,
    tier: 'B', gravedad: { texto: 'Baja', numerica: 1 },
    incidenciaActual: 3.0, incidenciaAnterior: 3.5, cambio: -14.3, cambioFormateado: '(-14.3%)',
    tendencia: 'estable', temporadaAlta: false, historicalTier: 'Low', weekOfYear: 14,
    diasDesdeUltimaFumigacion: 14, numRondas: 2,
    why: 'Gravedad Baja (3%) para Mosca del ovario, sin umbral económico validado, estable',
    bracket: 5,
  },
];
