import { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import { Download, Loader2, FileText, Eye, Presentation, ChevronLeft, ChevronRight, X } from 'lucide-react';
import { Button } from '../ui/button';
import { Badge } from '../ui/badge';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '../ui/table';
import { toast } from 'sonner';
import {
  fetchHistorialReportes,
  descargarReportePDF,
  descargarReporteDesdeHTML,
  fetchReporteHTML,
  descargarBlob,
} from '../../utils/reporteSemanalService';
import type { ReporteSemanalMetadata } from '../../types/reporteSemanal';
import { formatearFechaCorta, formatearFechaHora } from '../../utils/fechas';

function SlideFrame({ html, scale }: { html: string; scale: number }) {
  const srcDoc = `<!DOCTYPE html><html><head><style>body{margin:0;overflow:hidden;width:1280px;}</style></head><body>${html}</body></html>`;
  return (
    <div style={{ width: Math.floor(1280 * scale), height: Math.floor(720 * scale), overflow: 'hidden', flexShrink: 0 }}>
      <iframe
        title="Slide preview"
        srcDoc={srcDoc}
        sandbox="allow-same-origin"
        style={{
          width: 1280,
          height: 720,
          border: 'none',
          transform: `scale(${scale})`,
          transformOrigin: 'top left',
          display: 'block',
        }}
      />
    </div>
  );
}

export function HistorialReportes() {
  const [reportes, setReportes] = useState<ReporteSemanalMetadata[]>([]);
  const [loading, setLoading] = useState(true);
  const [descargando, setDescargando] = useState<string | null>(null);
  const [cargandoHTML, setCargandoHTML] = useState<string | null>(null);

  // Preview state
  const [previewHTML, setPreviewHTML] = useState('');
  const [previewSemana, setPreviewSemana] = useState('');
  const [slideActual, setSlideActual] = useState(0);
  const [slideScale, setSlideScale] = useState(1);
  const [presentando, setPresentando] = useState(false);
  const slideContainerRef = useRef<HTMLDivElement>(null);
  const presentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    cargarHistorial();
  }, []);

  const cargarHistorial = async () => {
    try {
      setLoading(true);
      const data = await fetchHistorialReportes();
      setReportes(data);
    } catch {
      toast.error('Error al cargar historial de reportes');
    } finally {
      setLoading(false);
    }
  };

  // Parse slides from HTML — content is trusted (generated by our own edge function)
  const slidesHtml = useMemo(() => {
    if (!previewHTML) return [];
    const parser = new DOMParser();
    const doc = parser.parseFromString(previewHTML, 'text/html');
    const styleContent = Array.from(doc.querySelectorAll('style')).map(s => s.outerHTML).join('\n');
    const slideEls = doc.querySelectorAll('.slide');
    return Array.from(slideEls).map(el => styleContent + el.outerHTML);
  }, [previewHTML]);

  const totalSlides = slidesHtml.length;

  const irASlide = useCallback((idx: number) => {
    setSlideActual(Math.max(0, Math.min(idx, totalSlides - 1)));
  }, [totalSlides]);

  // Scale slide to fit container
  useEffect(() => {
    if (!previewHTML) return;
    const updateScale = () => {
      if (presentando) {
        // Use window dimensions for fullscreen — leave room for nav bar
        const w = window.innerWidth / 1280;
        const h = (window.innerHeight - 48) / 720;
        setSlideScale(Math.min(w, h));
      } else if (slideContainerRef.current) {
        setSlideScale(slideContainerRef.current.offsetWidth / 1280);
      }
    };
    updateScale();
    // Re-compute on resize (covers fullscreen transitions)
    window.addEventListener('resize', updateScale);
    const container = slideContainerRef.current;
    const observer = container ? new ResizeObserver(updateScale) : null;
    if (container) observer?.observe(container);
    return () => {
      window.removeEventListener('resize', updateScale);
      observer?.disconnect();
    };
  }, [previewHTML, presentando]);

  // Keyboard nav for preview/present
  useEffect(() => {
    if (!previewHTML) return;
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'ArrowLeft') irASlide(slideActual - 1);
      else if (e.key === 'ArrowRight' || e.key === ' ') { e.preventDefault(); irASlide(slideActual + 1); }
      else if (e.key === 'Escape') { setPresentando(false); setPreviewHTML(''); }
    };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [previewHTML, slideActual, irASlide]);

  // Fullscreen management
  useEffect(() => {
    if (presentando && presentRef.current) {
      presentRef.current.requestFullscreen?.().catch(() => {});
    }
    const onFSChange = () => {
      if (!document.fullscreenElement) setPresentando(false);
    };
    document.addEventListener('fullscreenchange', onFSChange);
    return () => document.removeEventListener('fullscreenchange', onFSChange);
  }, [presentando]);

  const handleLoadHTML = async (reporte: ReporteSemanalMetadata, mode: 'ver' | 'presentar') => {
    try {
      setCargandoHTML(reporte.id);
      const html = await fetchReporteHTML(reporte);
      setPreviewHTML(html);
      setPreviewSemana(`S${String(reporte.numero_semana).padStart(2, '0')} — ${formatearFechaCorta(reporte.fecha_inicio)} a ${formatearFechaCorta(reporte.fecha_fin)}`);
      setSlideActual(0);
      if (mode === 'presentar') setPresentando(true);
    } catch {
      toast.error('Este reporte no tiene vista previa disponible');
    } finally {
      setCargandoHTML(null);
    }
  };

  const handleDescargar = async (reporte: ReporteSemanalMetadata) => {
    try {
      setDescargando(reporte.id);
      const filename = `reporte-semana-${reporte.ano || ''}-S${String(reporte.numero_semana).padStart(2, '0')}.pdf`;
      if (reporte.html_storage) {
        await descargarReporteDesdeHTML(reporte.html_storage, filename);
      } else {
        const blob = await descargarReportePDF(reporte.url_storage);
        descargarBlob(blob, filename);
      }
      toast.success('PDF descargado');
    } catch {
      toast.error('Error al descargar el reporte');
    } finally {
      setDescargando(null);
    }
  };

  const closePreview = () => {
    setPreviewHTML('');
    setPresentando(false);
  };


  // ============================================================================
  // RENDER: MAIN
  // ============================================================================

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="w-6 h-6 text-primary animate-spin" />
      </div>
    );
  }

  if (reportes.length === 0) {
    return (
      <div className="text-center py-12 text-gray-400">
        <FileText className="w-12 h-12 mx-auto mb-3 opacity-50" />
        <p>No hay reportes generados aún</p>
      </div>
    );
  }

  return (
    <>
      {/* Slide preview (inline) */}
      {previewHTML && !presentando && (
        <div className="mb-6 rounded-xl border border-border overflow-hidden bg-white">
          <div className="flex items-center justify-between px-4 py-2 bg-muted border-b border-border">
            <span className="text-sm font-medium text-foreground">{previewSemana}</span>
            <div className="flex items-center gap-2">
              <Button size="sm" variant="outline" onClick={() => setPresentando(true)}>
                <Presentation className="w-4 h-4 mr-1.5" />Presentar
              </Button>
              <Button size="sm" variant="ghost" onClick={closePreview}>
                <X className="w-4 h-4" />
              </Button>
            </div>
          </div>
          <div ref={slideContainerRef} style={{ position: 'relative', overflow: 'hidden', width: '100%', aspectRatio: '16/9' }}>
            {slidesHtml[slideActual] && <SlideFrame html={slidesHtml[slideActual]} scale={slideScale} />}
          </div>
          {/* Nav controls */}
          <div className="flex items-center justify-center gap-4 py-2 border-t border-border">
            <button onClick={() => irASlide(slideActual - 1)} disabled={slideActual === 0} className="text-foreground disabled:opacity-30">
              <ChevronLeft size={22} />
            </button>
            <span className="text-sm font-medium text-foreground">{slideActual + 1} / {totalSlides}</span>
            <button onClick={() => irASlide(slideActual + 1)} disabled={slideActual === totalSlides - 1} className="text-foreground disabled:opacity-30">
              <ChevronRight size={22} />
            </button>
          </div>
        </div>
      )}

      {/* Fullscreen presentation */}
      {presentando && (
        <div ref={presentRef} style={{ position: 'fixed', inset: 0, zIndex: 9999, background: '#000', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }}>
          <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', width: '100%' }}>
            {slidesHtml[slideActual] && <SlideFrame html={slidesHtml[slideActual]} scale={slideScale} />}
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 16, padding: '8px 0', color: '#fff' }}>
            <button onClick={() => irASlide(slideActual - 1)} disabled={slideActual === 0} style={{ opacity: slideActual === 0 ? 0.3 : 1, background: 'none', border: 'none', color: '#fff', cursor: 'pointer' }}>
              <ChevronLeft size={24} />
            </button>
            <span style={{ fontSize: 14, fontWeight: 500 }}>{slideActual + 1} / {totalSlides}</span>
            <button onClick={() => irASlide(slideActual + 1)} disabled={slideActual === totalSlides - 1} style={{ opacity: slideActual === totalSlides - 1 ? 0.3 : 1, background: 'none', border: 'none', color: '#fff', cursor: 'pointer' }}>
              <ChevronRight size={24} />
            </button>
            <button onClick={() => { document.exitFullscreen?.(); setPresentando(false); }} style={{ marginLeft: 16, background: 'none', border: 'none', color: '#fff', cursor: 'pointer' }}>
              <X size={20} />
            </button>
          </div>
        </div>
      )}

      {/* Report list */}
      <div className="overflow-x-auto">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Semana</TableHead>
              <TableHead>Período</TableHead>
              <TableHead className="hidden sm:table-cell">Generado por</TableHead>
              <TableHead className="hidden sm:table-cell">Fecha</TableHead>
              <TableHead className="text-right">Acciones</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {reportes.map(reporte => (
              <TableRow key={reporte.id}>
                <TableCell>
                  <Badge variant="secondary">
                    S{String(reporte.numero_semana).padStart(2, '0')}
                  </Badge>
                </TableCell>
                <TableCell className="text-sm text-gray-600 whitespace-nowrap">
                  {formatearFechaCorta(reporte.fecha_inicio)} — {formatearFechaCorta(reporte.fecha_fin)}
                </TableCell>
                <TableCell className="text-sm hidden sm:table-cell">
                  {reporte.generado_por_nombre || '-'}
                </TableCell>
                <TableCell className="text-sm text-gray-500 hidden sm:table-cell">
                  {formatearFechaHora(reporte.created_at)}
                </TableCell>
                <TableCell className="text-right">
                  <div className="flex items-center justify-end gap-1.5">
                    {reporte.html_storage && (
                      <>
                        <Button
                          size="sm"
                          variant="ghost"
                          title="Ver"
                          onClick={() => handleLoadHTML(reporte, 'ver')}
                          disabled={cargandoHTML === reporte.id}
                        >
                          {cargandoHTML === reporte.id ? (
                            <Loader2 className="w-4 h-4 animate-spin" />
                          ) : (
                            <Eye className="w-4 h-4" />
                          )}
                        </Button>
                        <Button
                          size="sm"
                          variant="ghost"
                          title="Presentar"
                          onClick={() => handleLoadHTML(reporte, 'presentar')}
                          disabled={cargandoHTML === reporte.id}
                        >
                          <Presentation className="w-4 h-4" />
                        </Button>
                      </>
                    )}
                    <Button
                      size="sm"
                      variant="outline"
                      title="Descargar PDF"
                      onClick={() => handleDescargar(reporte)}
                      disabled={descargando === reporte.id}
                    >
                      {descargando === reporte.id ? (
                        <Loader2 className="w-4 h-4 animate-spin" />
                      ) : (
                        <Download className="w-4 h-4" />
                      )}
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </>
  );
}
