-- =============================================================================
-- 078_kv_store_indices_duplicados.sql
--
-- `kv_store_1ccce916` (item 6 del issue 96) tiene 19 indices sobre `key` en una
-- tabla vacia de 152 kB: 18 identicos entre si mas el de la PRIMARY KEY.
-- Higiene, no incidente.
--
-- Estado verificado en produccion (2026-08-03):
--   kv_store_1ccce916_pkey        UNIQUE btree (key)                  <- constraint
--   kv_store_1ccce916_key_idx     btree (key text_pattern_ops)
--   kv_store_1ccce916_key_idx1..17  btree (key text_pattern_ops)      <- 17 copias
--
-- Investigacion previa (ver reporte del PR): grep completo de ambos arboles de
-- la edge function (src/supabase/functions/server/ y
-- supabase/functions/make-server-1ccce916/) y de todo el repo por
-- "CREATE INDEX" / "kv_store_1ccce916". El unico archivo que toca esa tabla es
-- kv_store.tsx, marcado "AUTOGENERATED FILE - DO NOT EDIT CONTENTS" por Figma
-- Make: expone unicamente get/set/del/mset/mget/mdel/getByPrefix sobre
-- PostgREST, sin ningun DDL. No hay migracion en `src/sql/migrations/` ni en
-- `supabase/migrations/` que cree la tabla o sus indices. Conclusion: los
-- indices NO fueron creados por codigo versionado en este repo -- son un
-- artefacto del bootstrap de la plataforma Figma Make (fuera del control de
-- version), asi que NO hay una sentencia CREATE INDEX que corregir del lado de
-- codigo. Esta migracion resuelve el sintoma en la base de datos; no existe un
-- companion fix porque no existe una causa raiz versionada.
--
-- -----------------------------------------------------------------------------
-- POR QUE NO SE BORRAN LOS 18
-- -----------------------------------------------------------------------------
-- El indice `key text_pattern_ops` NO es redundante con el de la PRIMARY KEY.
-- La PK es un btree con la clase de operadores por defecto, que en una
-- colacion distinta de C no puede servir un `LIKE 'prefijo%'`. Y ese es
-- exactamente el acceso que hace `getByPrefix()` en kv_store.tsx:
--
--     supabase.from("kv_store_1ccce916").select("key, value").like("key", prefix + "%")
--
-- Por eso se conserva UNA copia de `key text_pattern_ops` y se borran las otras
-- 17. Borrar las 18 dejaria `getByPrefix` sin indice utilizable: hoy es
-- inofensivo (la tabla esta vacia) pero seria una regresion latente de
-- rendimiento sembrada a proposito.
--
-- -----------------------------------------------------------------------------
-- COMO ELIGE QUE BORRAR
-- -----------------------------------------------------------------------------
-- No se asumen nombres: los duplicados los nombra Postgres automaticamente
-- (_key_idx, _key_idx1, ... _key_idx17) y ese patron no es contrato. La
-- migracion agrupa los indices de la tabla por su DEFINICION normalizada (el
-- `indexdef` sin el nombre) y, dentro de cada grupo, conserva uno y borra el
-- resto. Nunca toca un indice que respalde una constraint
-- (pg_constraint.conindid), porque DROP INDEX falla sobre esos.
--
-- Resultado esperado: 17 indices borrados, quedan 2 (el de la PK y una copia de
-- `key text_pattern_ops`).
--
-- Idempotente: al re-ejecutarse cada grupo ya tiene un solo miembro y no borra
-- nada.
-- =============================================================================

DO $$
DECLARE
  v_tabla    CONSTANT text := 'kv_store_1ccce916';
  v_esquema  CONSTANT text := 'public';
  v_idx      record;
  v_borrados integer := 0;
BEGIN
  -- Si la tabla no existe (p.ej. entorno de desarrollo sin datos de Figma
  -- Make), no hay nada que limpiar.
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables
     WHERE schemaname = v_esquema AND tablename = v_tabla
  ) THEN
    RAISE NOTICE 'Tabla %.% no existe, nada que limpiar.', v_esquema, v_tabla;
    RETURN;
  END IF;

  FOR v_idx IN
    WITH indices AS (
      SELECT
        pi.indexname,
        -- definicion sin el nombre del indice: dos indices con la misma
        -- definicion normalizada son duplicados exactos entre si.
        replace(pi.indexdef, ' INDEX ' || quote_ident(pi.indexname) || ' ', ' INDEX ') AS def_normalizada,
        -- los indices de constraint nunca se borran y ademas no compiten:
        -- se excluyen antes de agrupar.
        EXISTS (
          SELECT 1
            FROM pg_class c
            JOIN pg_namespace n ON n.oid = c.relnamespace
            JOIN pg_constraint pc ON pc.conindid = c.oid
           WHERE c.relname = pi.indexname
             AND n.nspname = pi.schemaname
        ) AS es_constraint
        FROM pg_indexes pi
       WHERE pi.schemaname = v_esquema
         AND pi.tablename  = v_tabla
    )
    SELECT indexname
      FROM (
        SELECT
          indexname,
          row_number() OVER (
            PARTITION BY def_normalizada
            ORDER BY length(indexname), indexname
          ) AS rn
          FROM indices
         WHERE NOT es_constraint
      ) ranked
     WHERE rn > 1          -- conserva el primero de cada grupo, borra el resto
     ORDER BY indexname
  LOOP
    EXECUTE format('DROP INDEX IF EXISTS %I.%I', v_esquema, v_idx.indexname);
    v_borrados := v_borrados + 1;
  END LOOP;

  RAISE NOTICE 'Indices duplicados eliminados en %.%: %', v_esquema, v_tabla, v_borrados;
END $$;

-- =============================================================================
-- VERIFICACION
-- =============================================================================
DO $$
DECLARE
  v_total       integer;
  v_prefijo     integer;
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_tables
     WHERE schemaname = 'public' AND tablename = 'kv_store_1ccce916'
  ) THEN
    RETURN;
  END IF;

  SELECT count(*) INTO v_total
    FROM pg_indexes
   WHERE schemaname = 'public' AND tablename = 'kv_store_1ccce916';

  SELECT count(*) INTO v_prefijo
    FROM pg_indexes
   WHERE schemaname = 'public' AND tablename = 'kv_store_1ccce916'
     AND indexdef ILIKE '%text_pattern_ops%';

  -- Debe quedar exactamente un indice por definicion distinta.
  IF v_prefijo <> 1 THEN
    RAISE EXCEPTION
      'Se esperaba exactamente 1 indice text_pattern_ops sobre kv_store_1ccce916, hay %. getByPrefix() se quedaria sin indice.',
      v_prefijo;
  END IF;

  RAISE NOTICE 'kv_store_1ccce916: % indices restantes (1 de PK + 1 text_pattern_ops).', v_total;
END $$;

-- Chequeo manual, copiable:
--   SELECT indexname, indexdef FROM pg_indexes
--    WHERE tablename = 'kv_store_1ccce916' ORDER BY indexname;

-- =============================================================================
-- ROLLBACK
-- =============================================================================
-- No aplica en sentido estricto: lo eliminado eran copias byte a byte de un
-- indice que sigue existiendo, asi que no se perdio ninguna capacidad de
-- acceso. Si hiciera falta recrear el indice de prefijo desde cero:
--   CREATE INDEX IF NOT EXISTS kv_store_1ccce916_key_idx
--     ON public.kv_store_1ccce916 USING btree (key text_pattern_ops);
-- =============================================================================
